### ISSUE TITLE
Is this working with Godot 4.0 and is it acitvly maintained?

### ISSUE THREAD

**Issue by kragil** [supabase-community/godot-engine.supabase#59]
Maybe improve the documentation. It is not clear if this works with Godot 4. Thank you.

**Comment by fenix-hub** [comment]
From the Readme you can see that on branch `main` there's the 3.x source code, but there's also a link to the 4.x version.
https://github.com/supabase-community/godot-engine.supabase/tree/4.x

**Comment by kragil** [comment]
I thought that is for Superbase version 3 and 4. That wasn't obvious to me. Sorry.
