### ISSUE TITLE
Error mesage: Could not resolve class "BaseTask"

### ISSUE THREAD

**Issue by BurSari92** [supabase-community/godot-engine.supabase#60]
Hi,

first of thank you for working on this very useful addon.
I am using the latest stable version of Godot 4.0 and the very new version of your addon.
But I always get the error message "Could not resolve class "BaseTask"", and unfortunately can´t fix it by myself.

Hope you can help out, I really want to use this addon on a bigger project.
Thanks in advance!

**Comment by BurSari92** [comment]
The error mesage above involving the "BaeTask" issue is inside the auth_task.gd script btw.


I was looking up the base_task.gd script and found out, that there is also an error message involving this line:

On Line 36:         httprequest.request(_endpoint, _headers, true, _method, _payload)

"Too many arguments for "request()" call. Expected at most 4 but received 5"

So there seems to be 1 argument to many. Which one is the "not needed" one?

**Comment by sindrsh** [comment]
@BurSari92, remove "true".
