### ISSUE TITLE
Add new storage features introduced in LW7 updates

### ISSUE THREAD

**Issue by dshukertjr** [supabase-community/godot-engine.supabase#62]
# Feature request

Hi there,

There has been some features added to our storage, and we made some changes to the js client library to be able to use those features. It would be great if these could be added to this client library as well!

- https://github.com/supabase/storage-js/pull/151 file size and mime type limits per bucket
- https://github.com/supabase/storage-js/pull/152 signed url for uploads
- https://github.com/supabase/storage-js/pull/145 quality option for image transformations
- https://github.com/supabase/storage-js/pull/142 format option for image transformation

**Comment by fenix-hub** [comment]
Hi @dshukertjr 
Thank you for opening this, very useful.
I'll make sure to align this library to the js SDK asap. 
Thanks :)

**Comment by fenix-hub** [comment]
closed by:
#09e557e2ba5ffc17954dd82b345dbe62eb5fdc1a
#5da55178e9c65206acd7fb558ceb3741e0147a62
#ac34e9a457889d37780a7ba3b6822c4f78195442
#90a057282f18ab1b3f78930386d37caa51a3fe11
