### ISSUE TITLE
Remove Print after Select

### ISSUE THREAD

**Issue by brwxisme** [supabase-community/godot-engine.supabase#69]
# Feature request

## Is your feature request related to a problem? Please describe.

To keep my debug output clean

## Describe the solution you'd like

Pls tell me how to disable this

## Describe alternatives you've considered

I've looking through the supabase scripts, cant find which one is keeps on printing

**Comment by brwxisme** [comment]
SORRY I WAS STUPID
turns out it was on an error from y ends
:)

**Comment by fenix-hub** [comment]
No worries!
